import { Project } from './types';

export const projects: Project[] = [
  {
    title: 'TaskFlow – Task Management Platform',
    src: 'Taskflow.png',
    color: '#d1fae5',
    url: 'https://taskflow.apnimandi.us/',
    slug: 'taskflow',
    role: 'Full Stack Developer',
    description:
      'A real-time task management platform built to replace over-engineered tools like Jira for small teams. Supports drag-and-drop task boards, team collaboration, workflow automation, and role-based access control.',
    techStack: [
      'React',
      'Node.js',
      'MongoDB',
      'Express',
      'Socket.io',
      'JWT',
      'RBAC',
      'Tailwind CSS',
    ],
    learnings: [
      'Built real-time collaboration using WebSockets — learned how to handle conflict resolution when multiple users edit simultaneously',
      'Designed a multi-role permission system (admin, member, viewer) with granular access control',
      'Implemented drag-and-drop with optimistic UI updates for instant feedback without waiting for server confirmation',
    ],
    website: 'https://taskflow.apnimandi.us/',
    github: 'https://github.com/VishalAggarwal2',
  },
  {
    title: 'Go Garbage Collector – Built from Scratch',
    src: 'Go.png',
    color: '#e0f2fe',
    url: 'https://github.com/VishalAggarwal2/GarbageCollectorSimulator',
    slug: 'go-garbage-collector',
    role: 'Systems Engineer',
    description:
      'A mark-and-sweep garbage collector implemented in Go from scratch. Built to deeply understand how memory management works under the hood — heap allocation, object graphs, reachability analysis, and GC pause times.',
    techStack: ['Go', 'Systems Programming', 'Memory Management', 'Data Structures'],
    learnings: [
      'Implemented mark-and-sweep in two phases: DFS traversal to mark live objects, then sweep to reclaim unreachable memory',
      'Learned how GC pause times emerge and why generational GC exists as an optimization',
      'Deep understanding of heap layout, pointer chasing, and why Go uses a tricolor marking algorithm in production',
    ],
    github: 'https://github.com/VishalAggarwal2/GarbageCollectorSimulator',
  },
  {
    title: 'Phoenix Portal – LNMIIT',
    src: 'Phoenix.png',
    color: '#bfdbfe',
    url: 'https://phoenix.lnmiit.ac.in/',
    slug: 'phoenix-portal',
    role: 'Full Stack Developer & Product Owner',
    description:
      'A full-featured university platform serving 10,000+ students and faculty at LNMIIT. Responsible for both technical architecture and product scoping — from defining requirements to production deployment.',
    techStack: ['Java', 'Spring Boot', 'React', 'MySQL', 'Multithreading', 'System Design'],
    learnings: [
      'Designed the system architecture to handle peak-load scenarios (exam results, semester registration rushes)',
      'Learned how to scope a product with real stakeholders — faculty, students, and admin — with conflicting requirements',
      'Applied multithreading to parallelize heavy backend operations without blocking the main request thread',
    ],
    website: 'https://phoenix.lnmiit.ac.in/',
  },
  {
    title: 'CI/CD Pipeline with Jenkins & ArgoCD',
    src: 'CiCd.png',
    color: '#fef3c7',
    url: 'https://github.com/VishalAggarwal2',
    slug: 'cicd-pipeline',
    role: 'DevOps Engineer',
    description:
      'End-to-end CI/CD pipeline built at Bajaj Finserv Health. Automated the entire build, test, and deployment workflow — eliminating manual release steps and reducing deployment risk. Paired with a full Prometheus + Grafana observability stack.',
    techStack: [
      'Jenkins',
      'ArgoCD',
      'Docker',
      'Kubernetes',
      'Prometheus',
      'Grafana',
      'Linux',
      'Bash',
    ],
    learnings: [
      'Built a multi-stage Jenkins pipeline: compile → unit test → integration test → Docker build → push → ArgoCD sync',
      'Set up Grafana dashboards and Prometheus alerting to reduce mean time to detection (MTTD) for production incidents',
      'Learned GitOps principles — ArgoCD syncs cluster state from Git, making deployments auditable and rollback trivial',
    ],
    github: 'https://github.com/VishalAggarwal2',
  },
  {
    title: 'Apni Mandi – HRM & Inventory System',
    src: 'sentiment.png',
    color: '#ddd6fe',
    url: 'https://www.apnimandi.com/',
    slug: 'apni-mandi',
    role: 'Full Stack Developer',
    description:
      'Built an HRM and Inventory Management System for a US-based agriculture marketplace (Apni Mandi) via Heydo Tech. Integrated third-party APIs including Twilio for SMS communications and Revel Systems for POS integration.',
    techStack: [
      'Node.js',
      'React',
      'MongoDB',
      'Spring Boot',
      'Twilio API',
      'Revel API',
      'JWT',
      'RBAC',
      'PM2',
    ],
    learnings: [
      'Integrated Twilio for automated SMS notifications — learned webhook handling and message delivery reliability',
      'Connected Revel POS system via REST API to sync inventory and sales data in real time',
      'Designed RBAC system for three distinct user roles: buyer, seller, and admin — each with different data views and permissions',
    ],
    website: 'https://www.apnimandi.com/',
  },
];
