import { Project } from './types';

export const projects: Project[] = [
  {
    title: 'IntervAI – Mock Interviewer with Memory',
    src: 'Intervue.png',
    color: '#ede9fe',
    url: 'https://github.com/VishalAggarwal2',
    slug: 'interv-ai',
    role: 'Full Stack Developer',
    description:
      'An AI-powered mock interview platform that actually remembers you. Most interview tools forget you the moment you close the tab — IntervAI tracks your weak areas across sessions and makes sure the next interview drills you harder on exactly what tripped you up. It conducts role and company-specific interviews (Google, Amazon, Startup), scores every answer using the STAR framework, and builds a persistent memory of your gaps over time. The result is a compound prep loop: the more you practice, the smarter and more targeted the questions become.',
    techStack: [
      'Next.js 14',
      'Java Spring Boot',
      'Supabase',
      'PostgreSQL',
      'Claude API',
      'ElevenLabs',
      'Web Speech API',
      'Upstash Redis',
      'AWS S3',
      'AWS CloudFront',
      'Clerk Auth',
      'Stripe',
      'Tailwind CSS',
      'Framer Motion',
      'Recharts',
      'shadcn/ui',
      'PDF.js',
      'Socket.io',
      'PostHog',
      'Sentry',
    ],
    learnings: [
      "Designed the Weak Area Memory System — after each session, answers scoring below 6 are flagged, their topics extracted, and stored in the user profile. The next session's Claude prompt is injected with those weak topics so at least 40% of questions target the user's specific gaps, not generic ones",
      'Built a voice interview mode using Web Speech API for browser-based speech-to-text and ElevenLabs for AI voice output — the result is a realistic interview simulation where the AI speaks questions and the user answers by talking, with transcripts scored in real time',
      'Architected a full AWS cloud recording pipeline: MediaRecorder captures audio in-browser, a presigned S3 URL is generated server-side (15-min expiry), the client uploads directly to S3, and CloudFront serves playback globally with per-user scoped access',
      'Implemented the STAR Framework scoring engine using Claude — each answer is evaluated across Situation, Task, Action, and Result (0–2.5 each), with structured JSON output including specific feedback, strength tags, improvement notes, and topic labels for the memory system',
      'Built a Question Prediction Engine: users paste a job description, Claude analyzes the JD language and role signals, and outputs the top 10 most likely interview questions grouped by category — one click starts a session using those exact questions',
      "Designed a GitHub-style Performance Heatmap (52 weeks × 7 days) where each cell's color intensity reflects the user's average score that day, alongside a Topic Coverage Map showing which interview topics are blind spots vs. strengths at a glance",
    ],
    images: ['Intervue.png', 'Intervue2.png', 'Intervue3.png'],
    github: 'https://github.com/VishalAggarwal2/InterueMaster',
  },
  {
    title: 'VoiceAI – Sales Call Intelligence Platform',
    src: 'VoiceAi1.png',
    color: '#fff7ed',
    url: 'https://github.com/VishalAggarwal2/VoiceAi',
    slug: 'voice-ai',
    role: 'Full Stack Developer',
    description:
      'An AI-powered voice analytics platform that transcribes sales calls and surfaces deep intelligence from every conversation. Upload or record any audio file — VoiceAI runs it through a two-stage pipeline: OpenAI Whisper for transcription, then GPT-4o for structured analysis. In Sales mode, it evaluates executive performance across 8 dimensions, predicts conversion probability, tracks talk ratios, and flags every buying signal, objection, and follow-up action buried in the call.',
    techStack: [
      'Java 21',
      'Spring Boot 3.2',
      'Next.js 14',
      'TypeScript',
      'OpenAI Whisper',
      'GPT-4o',
      'Spring WebFlux',
      'H2 Database',
      'Recharts',
      'Framer Motion',
      'Tailwind CSS',
      'React Dropzone',
    ],
    learnings: [
      'Designed a two-stage AI pipeline: Whisper handles speech-to-text for 8+ audio formats (MP3, WAV, WebM, M4A, OGG, FLAC, AAC, MP4) and then a GPT-4o prompt in strict JSON mode extracts structured intelligence — the pipeline produces the same predictable schema regardless of call length or audio quality',
      'Built a Sales Analysis prompt that evaluates 8 executive dimensions (communication style, tone, listening, product knowledge, rapport, objection handling, confidence, closing skills) plus customer sentiment, engagement level, buying signals, objections, and pain points — all in a single GPT-4o call with a 3,500-token structured JSON schema',
      'Implemented conversion probability prediction with a confidence score — GPT-4o synthesises all signal categories (executive performance, customer engagement, sentiment trajectory) into a probability estimate plus the specific factors that drove it up or down',
      'Built a waveform-based real-time audio recorder in the browser using the Web Audio API frequency analyzer — users can record directly without leaving the app, with live visual feedback and a 50 MB file validation guard on both client and server',
      'Architected the backend with Spring WebFlux async HTTP client configured with 120-second timeouts to handle long Whisper processing windows without blocking Tomcat threads — all external API calls are non-blocking reactive streams',
      'Designed an aggregated Sales Analytics dashboard that pulls all SALES-type reports, calculates rolling averages across executive dimensions, and renders radar charts, talk-ratio pie charts, and trend bars using Recharts with Framer Motion entry animations',
    ],
    images: ['VoiceAi1.png', 'VoiceAi2.png', 'VoiceAi3.png', 'VoiceAi4.png', 'VoiceAi5.png'],
    github: 'https://github.com/VishalAggarwal2/VoiceAi',
  },
  {
    title: 'TaskFlow – Task Management Platform',
    src: 'Taskflow.png',
    color: '#d1fae5',
    url: 'https://taskflow.apnimandi.us/',
    slug: 'taskflow',
    role: 'Full Stack Developer',
    description:
      'A real-time task management platform built to replace over-engineered tools like Jira for small teams. Supports drag-and-drop task boards, team collaboration, workflow automation, and role-based access control.',
    techStack: [
      'React',
      'Node.js',
      'MongoDB',
      'Express',
      'Socket.io',
      'JWT',
      'RBAC',
      'Tailwind CSS',
    ],
    learnings: [
      'Built real-time collaboration using WebSockets — learned how to handle conflict resolution when multiple users edit simultaneously',
      'Designed a multi-role permission system (admin, member, viewer) with granular access control',
      'Implemented drag-and-drop with optimistic UI updates for instant feedback without waiting for server confirmation',
    ],
    images: ['Taskflow.png', 'Taskflow2.png', 'Taskflow3.png'],
    website: 'https://taskflow.apnimandi.us/',
    github: 'https://github.com/VishalAggarwal2',
  },
  {
    title: 'Go Garbage Collector – Built from Scratch',
    src: 'Go.png',
    color: '#e0f2fe',
    url: 'https://github.com/VishalAggarwal2/GarbageCollectorSimulator',
    slug: 'go-garbage-collector',
    role: 'Systems Engineer',
    description:
      'A mark-and-sweep garbage collector implemented in Go from scratch. Built to deeply understand how memory management works under the hood — heap allocation, object graphs, reachability analysis, and GC pause times.',
    techStack: ['Go', 'Systems Programming', 'Memory Management', 'Data Structures'],
    learnings: [
      'Implemented mark-and-sweep in two phases: DFS traversal to mark live objects, then sweep to reclaim unreachable memory',
      'Learned how GC pause times emerge and why generational GC exists as an optimization',
      'Deep understanding of heap layout, pointer chasing, and why Go uses a tricolor marking algorithm in production',
    ],
    github: 'https://github.com/VishalAggarwal2/GarbageCollectorSimulator',
  },
  {
    title: 'Phoenix Portal – LNMIIT',
    src: 'Phoenix.png',
    color: '#bfdbfe',
    url: 'https://phoenix.lnmiit.ac.in/',
    slug: 'phoenix-portal',
    role: 'Full Stack Developer & Product Owner',
    description:
      'A full-featured university platform serving 10,000+ students and faculty at LNMIIT. Responsible for both technical architecture and product scoping — from defining requirements to production deployment.',
    techStack: ['Java', 'Spring Boot', 'React', 'MySQL', 'Multithreading', 'System Design'],
    learnings: [
      'Designed the system architecture to handle peak-load scenarios (exam results, semester registration rushes)',
      'Learned how to scope a product with real stakeholders — faculty, students, and admin — with conflicting requirements',
      'Applied multithreading to parallelize heavy backend operations without blocking the main request thread',
    ],
    website: 'https://phoenix.lnmiit.ac.in/',
  },
  {
    title: 'CI/CD Pipeline with Jenkins & ArgoCD',
    src: 'CiCd.png',
    color: '#fef3c7',
    url: 'https://github.com/VishalAggarwal2',
    slug: 'cicd-pipeline',
    role: 'DevOps Engineer',
    description:
      'End-to-end CI/CD pipeline built at Bajaj Finserv Health. Automated the entire build, test, and deployment workflow — eliminating manual release steps and reducing deployment risk. Paired with a full Prometheus + Grafana observability stack.',
    techStack: [
      'Jenkins',
      'ArgoCD',
      'Docker',
      'Kubernetes',
      'Prometheus',
      'Grafana',
      'Linux',
      'Bash',
    ],
    learnings: [
      'Built a multi-stage Jenkins pipeline: compile → unit test → integration test → Docker build → push → ArgoCD sync',
      'Set up Grafana dashboards and Prometheus alerting to reduce mean time to detection (MTTD) for production incidents',
      'Learned GitOps principles — ArgoCD syncs cluster state from Git, making deployments auditable and rollback trivial',
    ],
    github: 'https://github.com/VishalAggarwal2',
  },
  {
    title: 'Apni Mandi – HRM & Inventory System',
    src: 'sentiment.png',
    color: '#ddd6fe',
    url: 'https://www.apnimandi.com/',
    slug: 'apni-mandi',
    role: 'Full Stack Developer',
    description:
      'Built an HRM and Inventory Management System for a US-based agriculture marketplace (Apni Mandi) via Heydo Tech. Integrated third-party APIs including Twilio for SMS communications and Revel Systems for POS integration.',
    techStack: [
      'Node.js',
      'React',
      'MongoDB',
      'Spring Boot',
      'Twilio API',
      'Revel API',
      'JWT',
      'RBAC',
      'PM2',
    ],
    learnings: [
      'Integrated Twilio for automated SMS notifications — learned webhook handling and message delivery reliability',
      'Connected Revel POS system via REST API to sync inventory and sales data in real time',
      'Designed RBAC system for three distinct user roles: buyer, seller, and admin — each with different data views and permissions',
    ],
    website: 'https://www.apnimandi.com/',
  },
];
