export const experiences = [
  {
    id: 1,
    company: 'LNMIIT',
    role: 'Summer Intern — Full Stack Developer',
    period: '2022 – 2023',
    type: 'Internship',
    color: '#3b82f6',
    description: [
      'Led full-stack development of Phoenix Portal, a platform serving 10,000+ active users across LNMIIT',
      'Focused on scalable system design, multithreading, and backend optimisation to handle peak-load traffic',
      'Documented engineering learnings through technical blogs on Medium covering performance, architecture, and product decisions',
    ],
    tech: ['Java', 'Spring Boot', 'React', 'MySQL', 'System Design', 'Multithreading'],
    link: 'https://phoenix.lnmiit.ac.in/',
  },
  {
    id: 2,
    company: 'Heydo Tech',
    role: 'Software Developer — US Client (Apni Mandi)',
    period: '2023 – 2024',
    type: 'Part-time',
    color: '#8b5cf6',
    description: [
      'Built HRM (Human Resource Management) and Inventory Management systems for a US-based agriculture marketplace client',
      'Integrated external APIs including Twilio (SMS/communications) and Revel Systems (POS)',
      'Defined buyer, seller, and admin user journeys from scratch — mapped all roles before writing a single line of code',
      'Implemented JWT authentication and RBAC for secure multi-role access across the platform',
    ],
    tech: [
      'Node.js',
      'React',
      'MongoDB',
      'Java Spring Boot',
      'Twilio API',
      'Revel API',
      'JWT',
      'RBAC',
    ],
    link: 'https://www.apnimandi.com/',
  },
  {
    id: 3,
    company: 'Bajaj Finserv Health',
    role: 'Software Development Intern',
    period: 'Summer 2024',
    type: 'Internship',
    color: '#ec4899',
    description: [
      "Worked on production backend systems in Java Spring Boot serving millions of users on India's largest health-tech platform",
      'Built and shipped an Android application now live on the App Store with 100,000+ downloads',
      'Led migration from REST to GraphQL, reducing API calls by 40% and improving client-side performance',
      'Solely owned and delivered a Utility Portal for real-time request/response inspection — end to end',
      'Designed CI/CD pipelines with Jenkins and ArgoCD; set up Prometheus and Grafana observability stack',
    ],
    tech: [
      'Java',
      'Spring Boot',
      'GraphQL',
      'Android',
      'Jenkins',
      'ArgoCD',
      'Prometheus',
      'Grafana',
    ],
    link: 'https://www.bajajfinservhealth.in/',
  },
  {
    id: 4,
    company: 'Increff',
    role: 'Software Developer',
    period: '2024 – 2025',
    type: 'Full-time',
    color: '#10b981',
    description: [
      'Converted REST endpoints to GraphQL across the supply chain platform — first major task, shipped end to end',
      'Built the complete order cancellation workflow from scratch — designed the state machine, APIs, and UI flows',
      'Engineered a configurable UI workflow system where the frontend adapts dynamically based on backend configuration — no hardcoded UI logic',
      'Built a plug-and-play alerting system using Grafana and Prometheus — teams can set dynamic threshold alerts without touching code',
    ],
    tech: [
      'Java',
      'Spring Boot',
      'GraphQL',
      'React',
      'Grafana',
      'Prometheus',
      'Microservices',
      'PostgreSQL',
    ],
    link: 'https://www.increff.com/',
  },
];
